services:
  nodejs:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: "mysql -uroot -p$$MYSQL_ROOT_PASSWORD  -e 'SHOW databases'"
      interval: 10s
      retries: 3