services:
  nodejs:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: "mysql -uroot -p$$MYSQL_ROOT_PASSWORD  -e 'SHOW databases'"
      interval: 10s
      retries: 3
  # rabbitmq:
  #   image: rabbitmq
  #   healthcheck:
  #       test: ["CMD", "curl", "-f", "http://localhost:5672"]
  #       interval: 30s
  #       timeout: 10s
  #       retries: 5
  #   ports:
  #     - "0.0.0.0:5672:5672"
  #     - "0.0.0.0:15672:15672"
  #   networks:
  #     - app-tier